### ISSUE TITLE
多个图表在小程序scroll-view中，tooltip和legend的点击事件会失效

### ISSUE THREAD

**Issue by herofei** [antvis/wx-f2#206]
* **F2 Version**: 3.3.2
* **Platform**: abdroid、IOS和开发者工具
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

将仓库多个图表混合展示的示例中修改成如下
```css
/*  pages\charts\multiCharts */
#multi-bar-dom {
  width: 100%;
  height: 33%;
}

#multi-scatter-dom {
  width: 100%;  
  height: 33%;  
}

#multi-radial-dom {
  width: 100%;  
  height: 33%;  
}

ff-canvas {
  width: 100%;
  height: 100%;
}

.container {
  width: 100%;
  height: 600rpx;
  top: 200rpx;
}

.header {
  height: 200rpx;
  background: red;
}

.view-a {
  height: 600rpx;
  background: green;
}
```

```html
<!-- pages\charts\multiCharts -->

<view class="header"></view>
<scroll-view class="container" scroll-y>
  <view class="view-a"></view>
  <ff-canvas id="multi-bar-dom" canvas-id="multi-bar" opts="{{ drawBar }}"></ff-canvas>
  <ff-canvas id="multi-scatter-dom" canvas-id="multi-scatter" opts="{{ drawScatter }}"></ff-canvas>
  <ff-canvas id="multi-radial-dom" canvas-id="multi-radial" opts="{{ drawRadial }}"></ff-canvas>
</scroll-view>
```

按照如上修改代码，保存刷新，进入多图表好性能的示例，点击图表柱状图，发现tooltip不出现，点击legend，发现相关系列隐藏（或展示）的效果也不再出现
