### ISSUE TITLE
想将其中的一个图表进一步封装成自己的组件，但是在组件里引入会报错

### ISSUE THREAD

**Issue by TianJing555** [antvis/wx-f2#270]
将f2-canvas在组件中引用会报错，如图：
![image](https://user-images.githubusercontent.com/40845489/78352807-936e7a00-75db-11ea-9ba2-e542b585896f.png)
是不是引用时方法初始化的问题？
![image](https://user-images.githubusercontent.com/40845489/78352924-cc0e5380-75db-11ea-9112-3fc506f37a5f.png)
有没有解决方案呀

**Comment by IcebearDL** [comment]
内层外层的css加一下。
```js
<view class="container">
<canvas
  type="2d"
  class="f2-canvas"
  bindtouchstart="touchStart"
  bindtouchmove="touchMove"
  bindtouchend="touchEnd"
>
</canvas>
</view>
```
```css
.f2-canvas {
  width: 100%;
  height: 100%;
}

.container{
  width: 100%;
  height: 500rpx;
}
```
如果还没用就不知道了
